var ComponentTextures = 'progression_items:item/exposed'
var EtchedTextures = 'progression_items:item/etched'
var LogicCore = 'progression_items:item/logic_core'
var Primitive = 'progression_items:item/primitive'
StartupEvents.registry('item', event => {
    // event.create('exposed_cpu').displayName("Exposed Wafer").tooltip("Type: CPU").texture(ComponentTextures+'/cpu')
    // event.create('exposed_ram').displayName("Exposed Wafer").tooltip("Type: RAM").texture(ComponentTextures+'/ram')
    // event.create('exposed_ssd').displayName("Exposed Wafer").tooltip("Type: SDD").texture(ComponentTextures+'/ssd')
    // event.create('exposed_circuit').displayName("Exposed Wafer").tooltip("Type: Circuit").texture(ComponentTextures+'/circuit') 
    // event.create('etched_cpu').displayName("Etched Wafer").tooltip("Type: CPU").texture(EtchedTextures+'/cpu')
    // event.create('etched_ram').displayName("Etched Wafer").tooltip("Type: RAM").texture(EtchedTextures+'/ram')
    // event.create('etched_ssd').displayName("Etched Wafer").tooltip("Type: SDD").texture(EtchedTextures+'/ssd')
    // event.create('etched_circuit').displayName("Etched Wafer").tooltip("Type: Circuit").texture(EtchedTextures+'/circuit')
    event.create('etched_wafer').displayName("Etched Wafer")
    event.create('ruined_wafer').displayName("Ruined Wafer").tooltip(Text.gray('Type: Unidentifiable')).texture(ComponentTextures+'/broken_wafer').tooltip(Text.darkGray('§o"Why.. Why would you make this?"'))
    event.create('exposed_wafer').displayName("Exposed Wafer")
    event.create('silicon_wafer').displayName("Silicon Wafer").texture(ComponentTextures+'/blank_wafer')
    event.create('computer_chip_beta').displayName("Computationally Capable Wafer").texture(ComponentTextures+'/test_circuit')
    event.create('logic_core').displayName("Logic Core").texture('progression_items:item/logic_core/undoped_logic_core')
    event.create('bare_chip').displayName("Bare Chip").texture(ComponentTextures+'/test_circuit')
    event.create('computer_chip_alpha').displayName("Computer Chip").tooltip("'Now we're getting somewhere!'").texture(ComponentTextures+'/cpu')
    // Primitive - - -
    event.create('phenolic_paper').displayName("Phenolic Paper").texture('progression_items:item/primitive/phenolic_paper')
    event.create('phenolic_board').displayName("Phenolic Board").texture('progression_items:item/primitive/phenolic_board')
    event.create('pasted_board').displayName("Conductive Board").texture('progression_items:item/primitive/pasted_board')
    event.create('traced_circuit_board') // i don't know why, but this has a display name without it being declared. It scares me.
    event.create('housed_circuit_board').displayName("Housed Circuit Board").texture("progression_items:item/primitive/housed_second")
    event.create('primitive_circuit_board').displayName("Primitive Circuit Board").texture("progression_items:item/primitive/circuit_second")
    event.create('lead_frame').displayName("Lead Frame")
    event.create('old_copper_sheet').displayName("Flattened Copper Sheet").texture("progression_items:item/primitive/copper_sheet").tooltip(Text.gray('§o"Dejavu"')) 
    event.create('conductive_pellet').displayName("Conductive Pellet").texture('progression_items:item/primitive/pellet')
    event.create('pellet_mold').displayName("Pellet Mold").texture('progression_items:item/primitive/pellet_mask')
    event.create('modified_breadboard').displayName("Modified Breadboard").maxStackSize(1)

})  
StartupEvents.registry('fluid', event => {
    event.create('developer_solution')
    .thinTexture(0x2b1814)
    .bucketColor(0x2b1814)
    .displayName('Developer Solution')
    event.create('photo_resist')
    .thinTexture(0xE6C88A)
    .bucketColor(0xE6C88A)
    .displayName('Photo Resist')
    event.create('liquid_resin')
    .thinTexture(0xFFBF00)
    .bucketColor(0xFFBF00)
    .viscosity(9999)
    .displayName('Liquid Resin')
    event.create('conductive_paste')
    .thickTexture(0xa19d94)
    .bucketColor(0xa19d94)
    .viscosity(9999)
    .displayName('Conductive Paste')
    event.create('conductive_slurry')
    .thickTexture(0xaa8868)
    .bucketColor(0xaa8868)
    .viscosity(9999)
    .displayName('Conductive Slurry')
})